version: '3.1'

#networks:
  #my-network:
    #external: true

services:
  
  userdb:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=usersdatabase
    #networks:
      #- my-network

  userapi:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3001:3001'
    depends_on:
      - userdb
    volumes:
      - ./src:/app/src
    #networks:
      #- my-network